// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDEYHnnFsOkqIVd6JGNAd26g3BoEdEWJf8',
    appId: '1:545076155020:web:0442249c38907f57f4a1a9',
    messagingSenderId: '545076155020',
    projectId: 'flutter-project-9aae7',
    authDomain: 'flutter-project-9aae7.firebaseapp.com',
    storageBucket: 'flutter-project-9aae7.appspot.com',
    measurementId: 'G-7B3VSRPXZH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAdqhjbL8a5_Orj0nKiRHVfj1AoKS5IvlU',
    appId: '1:545076155020:android:dd1b22c34edf728bf4a1a9',
    messagingSenderId: '545076155020',
    projectId: 'flutter-project-9aae7',
    storageBucket: 'flutter-project-9aae7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBTKtwwoe2ndvE_av9_fOY8GvF6j4Kxqek',
    appId: '1:545076155020:ios:a5721e5dfcdc3441f4a1a9',
    messagingSenderId: '545076155020',
    projectId: 'flutter-project-9aae7',
    storageBucket: 'flutter-project-9aae7.appspot.com',
    iosClientId: '545076155020-5fv6mgkrqaugh4arjrp7ijatujl9tc63.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterNew',
  );
}
